# Generated by Django 3.1.7 on 2021-04-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210330_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activated',
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(null=True, upload_to='csv'),
        ),
    ]
